/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceId = IDL.Text;
export const ChildId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ChildProfile = IDL.Record({
  'id' : ChildId,
  'age' : IDL.Nat,
  'caregiverId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'deviceId' : DeviceId,
});
export const Alert = IDL.Record({
  'stressLevel' : IDL.Float64,
  'emotionState' : IDL.Text,
  'childId' : ChildId,
  'timestamp' : Timestamp,
  'childName' : IDL.Text,
});
export const ReadingId = IDL.Nat;
export const SensorReading = IDL.Record({
  'id' : ReadingId,
  'gsr' : IDL.Float64,
  'hrv' : IDL.Float64,
  'ppg' : IDL.Float64,
  'accelX' : IDL.Float64,
  'accelY' : IDL.Float64,
  'accelZ' : IDL.Float64,
  'stressLevel' : IDL.Float64,
  'childId' : ChildId,
  'motionIntensity' : IDL.Float64,
  'gyroX' : IDL.Float64,
  'gyroY' : IDL.Float64,
  'gyroZ' : IDL.Float64,
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
});
export const EmotionId = IDL.Nat;
export const EmotionResult = IDL.Record({
  'id' : EmotionId,
  'emotionState' : IDL.Text,
  'careSuggestions' : IDL.Vec(IDL.Text),
  'childId' : ChildId,
  'timestamp' : Timestamp,
  'rawResponse' : IDL.Text,
  'confidence' : IDL.Float64,
  'readingId' : ReadingId,
});
export const ChildDetail = IDL.Record({
  'recentReadings' : IDL.Vec(SensorReading),
  'emotionHistory' : IDL.Vec(EmotionResult),
  'profile' : IDL.Record({
    'id' : ChildId,
    'age' : IDL.Nat,
    'caregiverId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'deviceId' : DeviceId,
  }),
});
export const ChildSummary = IDL.Record({
  'id' : ChildId,
  'latestStressLevel' : IDL.Opt(IDL.Float64),
  'latestMotionIntensity' : IDL.Opt(IDL.Float64),
  'latestEmotion' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'latestTimestamp' : IDL.Opt(Timestamp),
});
export const SensorPayload = IDL.Record({
  'gsr' : IDL.Float64,
  'hrv' : IDL.Float64,
  'ppg' : IDL.Float64,
  'accelX' : IDL.Float64,
  'accelY' : IDL.Float64,
  'accelZ' : IDL.Float64,
  'stressLevel' : IDL.Float64,
  'motionIntensity' : IDL.Float64,
  'gyroX' : IDL.Float64,
  'gyroY' : IDL.Float64,
  'gyroZ' : IDL.Float64,
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'assignRole' : IDL.Func(
      [IDL.Principal, IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null })],
      [],
      [],
    ),
  'createChild' : IDL.Func([IDL.Text, IDL.Nat, DeviceId], [ChildProfile], []),
  'deleteChild' : IDL.Func([ChildId], [IDL.Bool], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getChild' : IDL.Func([ChildId], [IDL.Opt(ChildProfile)], ['query']),
  'getChildDetail' : IDL.Func([ChildId], [IDL.Opt(ChildDetail)], ['query']),
  'getEmotionHistory' : IDL.Func(
      [ChildId],
      [IDL.Vec(EmotionResult)],
      ['query'],
    ),
  'getMyChildren' : IDL.Func([], [IDL.Vec(ChildSummary)], ['query']),
  'getMyRole' : IDL.Func(
      [],
      [IDL.Opt(IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }))],
      ['query'],
    ),
  'getSensorReadings' : IDL.Func(
      [ChildId, Timestamp, Timestamp],
      [IDL.Vec(SensorReading)],
      ['query'],
    ),
  'ingestSensorData' : IDL.Func([SensorPayload], [EmotionResult], []),
  'register' : IDL.Func([], [], []),
  'updateChild' : IDL.Func(
      [ChildId, IDL.Text, IDL.Nat, DeviceId],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceId = IDL.Text;
  const ChildId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ChildProfile = IDL.Record({
    'id' : ChildId,
    'age' : IDL.Nat,
    'caregiverId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'deviceId' : DeviceId,
  });
  const Alert = IDL.Record({
    'stressLevel' : IDL.Float64,
    'emotionState' : IDL.Text,
    'childId' : ChildId,
    'timestamp' : Timestamp,
    'childName' : IDL.Text,
  });
  const ReadingId = IDL.Nat;
  const SensorReading = IDL.Record({
    'id' : ReadingId,
    'gsr' : IDL.Float64,
    'hrv' : IDL.Float64,
    'ppg' : IDL.Float64,
    'accelX' : IDL.Float64,
    'accelY' : IDL.Float64,
    'accelZ' : IDL.Float64,
    'stressLevel' : IDL.Float64,
    'childId' : ChildId,
    'motionIntensity' : IDL.Float64,
    'gyroX' : IDL.Float64,
    'gyroY' : IDL.Float64,
    'gyroZ' : IDL.Float64,
    'deviceId' : DeviceId,
    'timestamp' : Timestamp,
  });
  const EmotionId = IDL.Nat;
  const EmotionResult = IDL.Record({
    'id' : EmotionId,
    'emotionState' : IDL.Text,
    'careSuggestions' : IDL.Vec(IDL.Text),
    'childId' : ChildId,
    'timestamp' : Timestamp,
    'rawResponse' : IDL.Text,
    'confidence' : IDL.Float64,
    'readingId' : ReadingId,
  });
  const ChildDetail = IDL.Record({
    'recentReadings' : IDL.Vec(SensorReading),
    'emotionHistory' : IDL.Vec(EmotionResult),
    'profile' : IDL.Record({
      'id' : ChildId,
      'age' : IDL.Nat,
      'caregiverId' : IDL.Principal,
      'name' : IDL.Text,
      'createdAt' : Timestamp,
      'deviceId' : DeviceId,
    }),
  });
  const ChildSummary = IDL.Record({
    'id' : ChildId,
    'latestStressLevel' : IDL.Opt(IDL.Float64),
    'latestMotionIntensity' : IDL.Opt(IDL.Float64),
    'latestEmotion' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'latestTimestamp' : IDL.Opt(Timestamp),
  });
  const SensorPayload = IDL.Record({
    'gsr' : IDL.Float64,
    'hrv' : IDL.Float64,
    'ppg' : IDL.Float64,
    'accelX' : IDL.Float64,
    'accelY' : IDL.Float64,
    'accelZ' : IDL.Float64,
    'stressLevel' : IDL.Float64,
    'motionIntensity' : IDL.Float64,
    'gyroX' : IDL.Float64,
    'gyroY' : IDL.Float64,
    'gyroZ' : IDL.Float64,
    'deviceId' : DeviceId,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'assignRole' : IDL.Func(
        [IDL.Principal, IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null })],
        [],
        [],
      ),
    'createChild' : IDL.Func([IDL.Text, IDL.Nat, DeviceId], [ChildProfile], []),
    'deleteChild' : IDL.Func([ChildId], [IDL.Bool], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getChild' : IDL.Func([ChildId], [IDL.Opt(ChildProfile)], ['query']),
    'getChildDetail' : IDL.Func([ChildId], [IDL.Opt(ChildDetail)], ['query']),
    'getEmotionHistory' : IDL.Func(
        [ChildId],
        [IDL.Vec(EmotionResult)],
        ['query'],
      ),
    'getMyChildren' : IDL.Func([], [IDL.Vec(ChildSummary)], ['query']),
    'getMyRole' : IDL.Func(
        [],
        [IDL.Opt(IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null }))],
        ['query'],
      ),
    'getSensorReadings' : IDL.Func(
        [ChildId, Timestamp, Timestamp],
        [IDL.Vec(SensorReading)],
        ['query'],
      ),
    'ingestSensorData' : IDL.Func([SensorPayload], [EmotionResult], []),
    'register' : IDL.Func([], [], []),
    'updateChild' : IDL.Func(
        [ChildId, IDL.Text, IDL.Nat, DeviceId],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };