/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'stressLevel' : number,
  'emotionState' : string,
  'childId' : ChildId,
  'timestamp' : Timestamp,
  'childName' : string,
}
export interface ChildDetail {
  'recentReadings' : Array<SensorReading>,
  'emotionHistory' : Array<EmotionResult>,
  'profile' : {
    'id' : ChildId,
    'age' : bigint,
    'caregiverId' : Principal,
    'name' : string,
    'createdAt' : Timestamp,
    'deviceId' : DeviceId,
  },
}
export type ChildId = bigint;
export interface ChildProfile {
  'id' : ChildId,
  'age' : bigint,
  'caregiverId' : Principal,
  'name' : string,
  'createdAt' : Timestamp,
  'deviceId' : DeviceId,
}
export interface ChildSummary {
  'id' : ChildId,
  'latestStressLevel' : [] | [number],
  'latestMotionIntensity' : [] | [number],
  'latestEmotion' : [] | [string],
  'name' : string,
  'latestTimestamp' : [] | [Timestamp],
}
export type DeviceId = string;
export type EmotionId = bigint;
export interface EmotionResult {
  'id' : EmotionId,
  'emotionState' : string,
  'careSuggestions' : Array<string>,
  'childId' : ChildId,
  'timestamp' : Timestamp,
  'rawResponse' : string,
  'confidence' : number,
  'readingId' : ReadingId,
}
export type ReadingId = bigint;
export interface SensorPayload {
  'gsr' : number,
  'hrv' : number,
  'ppg' : number,
  'accelX' : number,
  'accelY' : number,
  'accelZ' : number,
  'stressLevel' : number,
  'motionIntensity' : number,
  'gyroX' : number,
  'gyroY' : number,
  'gyroZ' : number,
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
}
export interface SensorReading {
  'id' : ReadingId,
  'gsr' : number,
  'hrv' : number,
  'ppg' : number,
  'accelX' : number,
  'accelY' : number,
  'accelZ' : number,
  'stressLevel' : number,
  'childId' : ChildId,
  'motionIntensity' : number,
  'gyroX' : number,
  'gyroY' : number,
  'gyroZ' : number,
  'deviceId' : DeviceId,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'assignRole' : ActorMethod<
    [Principal, { 'admin' : null } | { 'user' : null }],
    undefined
  >,
  'createChild' : ActorMethod<[string, bigint, DeviceId], ChildProfile>,
  'deleteChild' : ActorMethod<[ChildId], boolean>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getChild' : ActorMethod<[ChildId], [] | [ChildProfile]>,
  'getChildDetail' : ActorMethod<[ChildId], [] | [ChildDetail]>,
  'getEmotionHistory' : ActorMethod<[ChildId], Array<EmotionResult>>,
  'getMyChildren' : ActorMethod<[], Array<ChildSummary>>,
  'getMyRole' : ActorMethod<[], [] | [{ 'admin' : null } | { 'user' : null }]>,
  'getSensorReadings' : ActorMethod<
    [ChildId, Timestamp, Timestamp],
    Array<SensorReading>
  >,
  'ingestSensorData' : ActorMethod<[SensorPayload], EmotionResult>,
  'register' : ActorMethod<[], undefined>,
  'updateChild' : ActorMethod<[ChildId, string, bigint, DeviceId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];