/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DeviceId = string;
export interface ChildDetail {
    recentReadings: Array<SensorReading>;
    emotionHistory: Array<EmotionResult>;
    profile: {
        id: ChildId;
        age: bigint;
        caregiverId: Principal;
        name: string;
        createdAt: Timestamp;
        deviceId: DeviceId;
    };
}
export type Timestamp = bigint;
export interface Alert {
    stressLevel: number;
    emotionState: string;
    childId: ChildId;
    timestamp: Timestamp;
    childName: string;
}
export type ChildId = bigint;
export interface SensorReading {
    id: ReadingId;
    gsr: number;
    hrv: number;
    ppg: number;
    accelX: number;
    accelY: number;
    accelZ: number;
    stressLevel: number;
    childId: ChildId;
    motionIntensity: number;
    gyroX: number;
    gyroY: number;
    gyroZ: number;
    deviceId: DeviceId;
    timestamp: Timestamp;
}
export interface SensorPayload {
    gsr: number;
    hrv: number;
    ppg: number;
    accelX: number;
    accelY: number;
    accelZ: number;
    stressLevel: number;
    motionIntensity: number;
    gyroX: number;
    gyroY: number;
    gyroZ: number;
    deviceId: DeviceId;
    timestamp: Timestamp;
}
export interface ChildSummary {
    id: ChildId;
    latestStressLevel?: number;
    latestMotionIntensity?: number;
    latestEmotion?: string;
    name: string;
    latestTimestamp?: Timestamp;
}
export interface EmotionResult {
    id: EmotionId;
    emotionState: string;
    careSuggestions: Array<string>;
    childId: ChildId;
    timestamp: Timestamp;
    rawResponse: string;
    confidence: number;
    readingId: ReadingId;
}
export type ReadingId = bigint;
export type EmotionId = bigint;
export interface ChildProfile {
    id: ChildId;
    age: bigint;
    caregiverId: Principal;
    name: string;
    createdAt: Timestamp;
    deviceId: DeviceId;
}
export enum Variant_admin_user {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    assignRole(user: Principal, role: Variant_admin_user): Promise<void>;
    createChild(name: string, age: bigint, deviceId: DeviceId): Promise<ChildProfile>;
    deleteChild(childId: ChildId): Promise<boolean>;
    getAlerts(): Promise<Array<Alert>>;
    getChild(childId: ChildId): Promise<ChildProfile | null>;
    getChildDetail(childId: ChildId): Promise<ChildDetail | null>;
    getEmotionHistory(childId: ChildId): Promise<Array<EmotionResult>>;
    getMyChildren(): Promise<Array<ChildSummary>>;
    getMyRole(): Promise<Variant_admin_user | null>;
    getSensorReadings(childId: ChildId, fromTimestamp: Timestamp, toTimestamp: Timestamp): Promise<Array<SensorReading>>;
    ingestSensorData(payload: SensorPayload): Promise<EmotionResult>;
    register(): Promise<void>;
    updateChild(childId: ChildId, name: string, age: bigint, deviceId: DeviceId): Promise<boolean>;
}
import type { ChildDetail as _ChildDetail, ChildId as _ChildId, ChildProfile as _ChildProfile, ChildSummary as _ChildSummary, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async assignRole(arg0: Principal, arg1: Variant_admin_user): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChild(arg0: string, arg1: bigint, arg2: DeviceId): Promise<ChildProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createChild(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChild(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteChild(arg0: ChildId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChild(arg0);
            return result;
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return result;
        }
    }
    async getChild(arg0: ChildId): Promise<ChildProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChild(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChild(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildDetail(arg0: ChildId): Promise<ChildDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildDetail(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildDetail(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionHistory(arg0: ChildId): Promise<Array<EmotionResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionHistory(arg0);
            return result;
        }
    }
    async getMyChildren(): Promise<Array<ChildSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChildren();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChildren();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Variant_admin_user | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSensorReadings(arg0: ChildId, arg1: Timestamp, arg2: Timestamp): Promise<Array<SensorReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSensorReadings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSensorReadings(arg0, arg1, arg2);
            return result;
        }
    }
    async ingestSensorData(arg0: SensorPayload): Promise<EmotionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.ingestSensorData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ingestSensorData(arg0);
            return result;
        }
    }
    async register(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register();
            return result;
        }
    }
    async updateChild(arg0: ChildId, arg1: string, arg2: bigint, arg3: DeviceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChild(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChild(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ChildSummary_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChildSummary): ChildSummary {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        admin: null;
    } | {
        user: null;
    }]): Variant_admin_user | null {
    return value.length === 0 ? null : from_candid_variant_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChildProfile]): ChildProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChildDetail]): ChildDetail | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChildId;
    latestStressLevel: [] | [number];
    latestMotionIntensity: [] | [number];
    latestEmotion: [] | [string];
    name: string;
    latestTimestamp: [] | [_Timestamp];
}): {
    id: ChildId;
    latestStressLevel?: number;
    latestMotionIntensity?: number;
    latestEmotion?: string;
    name: string;
    latestTimestamp?: Timestamp;
} {
    return {
        id: value.id,
        latestStressLevel: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.latestStressLevel)),
        latestMotionIntensity: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.latestMotionIntensity)),
        latestEmotion: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.latestEmotion)),
        name: value.name,
        latestTimestamp: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.latestTimestamp))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Variant_admin_user {
    return "admin" in value ? Variant_admin_user.admin : "user" in value ? Variant_admin_user.user : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChildSummary>): Array<ChildSummary> {
    return value.map((x)=>from_candid_ChildSummary_n5(_uploadFile, _downloadFile, x));
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_admin_user): {
    admin: null;
} | {
    user: null;
} {
    return value == Variant_admin_user.admin ? {
        admin: null
    } : value == Variant_admin_user.user ? {
        user: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
